version: '3'
services:
  telegram-feedback-bot:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    container_name: telegram-feedback-bot
    hostname: telegram-feedback-bot
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_BOT_WHITELIST=${TELEGRAM_BOT_WHITELIST}
      - ADMIN_CHAT_ID=${ADMIN_CHAT_ID}
